name: CI-PR

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      GODOT_BIN: godot
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Godot .NET
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.7.2
          use-dotnet: true

      - name: Build
        working-directory: src/eplugin-framework
        run: dotnet build "EPlugin Framework.sln" --configuration Debug

      - name: Run tests
        working-directory: src/eplugin-framework
        run: dotnet test "EPlugin Framework.sln" --configuration Debug --no-build
