name: CI-Release

on:
  push:
    tags:
      - "v*"

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 200
          fetch-tags: true
          
      - name: Initialize version
        shell: bash
        run: |
          echo "VERSION=$( git describe --tags | sed 's/v\(.*\)-\(.*\)/\1.\2/g' )" >> "$GITHUB_ENV"

      - name: Set Version to plugin.ini
        shell: bash
        run: |
          sed -i "s/version=\".*\"/version=\"${{ env.VERSION }}\"/g" src/eplugin-framework/addons/ePlugin/plugin.cfg

      - name: Create artifact
        shell: bash
        run: |
          mkdir out/
          cd src/eplugin-framework
          zip -r ../../out/ePlugin-v${VERSION}.zip addons/ePlugin

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v6.2.2
        with:
          mode: "HYBRID"
          configurationJson: |
            {
               "template": "#{{CHANGELOG}}\n\n<detail>\n<summary>Contributors</summary>\n\n#{{CONTRIBUTORS}}\n\n</detail>\n\n",
               "categories": [
                 {
                     "title": "## Feature",
                     "labels": ["feat", "feature"]
                 },
                 {
                     "title": "## Fix",
                     "labels": ["fix", "bug"]
                 },
                 {
                     "title": "## Other",
                     "labels": []
                 }
               ],
               "ignore_labels": [
                 "ignore"
               ],
               "label_extractor": [
                 {
                   "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                   "on_property": "title",
                   "target": "$1"
                 }
               ],
              "tag_resolver": {
                "method": "semver",
                "filter": {
                  "pattern": "v(.+)",
                  "flags": "gu"
                }
              }
             }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: "ePlugin-v${{ env.VERSION }}"
          body: ${{ steps.build_changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          artifacts: "out/ePlugin-v${{ env.VERSION }}.zip"

      